version: "3.9"
services:
  app:
    build: .
    container_name: flask-app
    expose:
    - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: flask-nginx
    ports:
    - "8081:80"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - app
    restart: always
